#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/lib/banner.sh"
source "$SCRIPT_DIR/lib/logger.sh"
source "$SCRIPT_DIR/lib/config.sh"

show_banner

source "$SCRIPT_DIR/lib/system_info.sh"
source "$SCRIPT_DIR/lib/animation.sh"

loading_animation "Scanning system"

show_system_info

COMMAND="${1:-menu}"

case "$COMMAND" in

    install)
        shift
        source "$SCRIPT_DIR/commands/install.sh"
        ;;
    
    update)
        source "$SCRIPT_DIR/commands/update.sh"
        ;;
    
    doctor)
        sourcee "$SCRIPT_DIR/commands/doctor.sh"
        ;;
    
    repair)
        source "$SCRIPT_DIR/commands/repair.sh"
        ;;
    
    backup)
        source "$SCRIPT_DIR/commands/backup.sh"
        ;;
    
    restore)
        source "$SCRIPT_DIR/commands/restore.sh"
        ;;

    menu)
        source "$SCRIPT_DIR/commands/menu.sh"
        handle_menu
        ;;
    
    uninstall)
        source "$SCRIPT_DIR/commands/uninstall.sh"
        ;;
    
    modules)
        source "$SCRIPT_DIR/commands/modules.sh"
        ;;
    
    profiles)
        source "$SCRIPT_DIR/commands/profiles.sh"
        ;;
    help)
        source "$SCRIPT_DIR/commands/help.sh"
        ;;

    *)
        echo "Unknown command: $COMMAND"
        ;;
esac