SYSTEM_PACKAGES=(
    git
    curl
    wget
    fastfetch
    btop
    gcc
    gcc-c++
    make
    cmake
)

TERMINAL_PACKAGES=(
    zsh
    fzf
    ripgrep
    bat
    eza
)

DEV_PACKAGES=(
    python3
    python3-pip
    java-21-openjdk
    nodejs
)