#!/usr/bin/env bash


PROFILE_mobile=(
    git
    java
    flutter
    vscode
)


PROFILE_backend=(
    git
    docker
    postgres
    vscode
)


PROFILE_web=(
    git
    node
    vscode
)


PROFILE_ai=(
    git
    docker
    python
    vscode
)


PROFILE_full=(
    git
    java
    docker
    flutter
    postgres
    vscode
)